### ISSUE TITLE
Works on 1650 MaxQ

### ISSUE THREAD

**Issue by berlinmitteinstitut** [xor2k/gpu_undervolt#3]
Great script, thanks for this! Can confirm in works in my Thinkpad X1 Extreme Gen2 with Pop OS 22.04. I added the following lines to your script on my private copy, it saves around 7-5 watts on my 35w GPU depending on the game.

` elif [ "$type" = "NVIDIA_GeForce_GTX_1650_with_Max-Q_Design" ]; then
            adjust_gpu $i 1595 220`

**Comment by xor2k** [comment]
Hi dear neighbour berlinmitteinstitut ;) One question: where did you get that 1595 Mhz clock from? According to Wikipedia, it is supposed to be lower:

https://www.notebookcheck.net/NVIDIA-GeForce-GTX-1650-Max-Q-GPU-Benchmarks-and-Specs.418763.0.html

For your GPU it should be around 1245. So 1595 seems pretty heavily overclocked to me. Can you try the lower value (1245) and tell whether there is any impact on performance?

Could also be that nvidia-smi simply ignores values which are too high.

**Comment by berlinmitteinstitut** [comment]
Hi Michael, I have these numbers from my GPU. Without any OC or UV in normally hovers around 1400 Mhz when 100% utilized, when the card is not fully utilized it goes up to 1830 Mhz. 1595 - 220 OC/UV leads back to the stable 1400 with power savings of around 20-30%. 
![image](https://user-images.githubusercontent.com/49810622/224087863-d6fce6eb-a6b5-441f-a918-149fcde87c89.png)

**Comment by xor2k** [comment]
Okay, added your line and referred to this discussion.
